load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "spectator",
    srcs = [
        "spectator/logger.cc",
        "spectator/publisher.cc",
    ],
    hdrs = [
        "spectator/config.h",
        "spectator/id.h",
        "spectator/logger.h",
        "spectator/measurement.h",
        "spectator/meter_type.h",
        "spectator/publisher.h",
        "spectator/registry.h",
        "spectator/stateful_meters.h",
        "spectator/stateless_meters.h",
        "spectator/valid_chars.inc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/time",
        "@asio",
        "@fmt//:fmt",
        "@spdlog//:spdlog",
    ],
)

cc_test(
    name = "spectator_test",
    srcs = glob([
        "spectator/*_test.cc",
        "spectator/test_*.cc",
        "spectator/test_*.h",
    ]),
    linkopts = select({
        "@bazel_tools//src/conditions:linux_x86_64": [
            "-lbfd",
            "-ldl",
        ],
        "//conditions:default": [],
    }),
    local_defines = select({
        "@bazel_tools//src/conditions:linux_x86_64": ["BACKWARD_HAS_BFD=1"],
        "//conditions:default": [],
    }),
    deps = [
        ":spectator",
        "@com_github_bombela_backward//:backward",
        "@com_google_googletest//:gtest",
    ],
)
