#!/bin/sh

bazel build spectator_compdb
outfile="$(bazel info bazel-bin)/compile_commands.json"
execroot=$(bazel info execution_root)
sed -i.bak "s@__EXEC_ROOT__@${execroot}@" "${outfile}"
echo "Compilation Database: ${outfile}"
