name: PR Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {compiler: gcc}
          - {compiler: clang}
    env:
      LANG: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v2

      - name: Build and Test (clang)
        if: startsWith(matrix.compiler, 'clang')
        env:
          CC: "clang-11"
          CXX: "clang++-11"
        run: ./run-build.sh

      - name: Install Dependencies (gcc)
        if: startsWith(matrix.compiler, 'gcc')
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y lcov

      - name: Build and Test (gcc)
        if: startsWith(matrix.compiler, 'gcc')
        env:
          CC: "gcc-10"
          CXX: "g++-10"
        run: ./run-build.sh
